services:
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pg_db
    volumes:
      - "./pg_db_data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
  postgres-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./pg_admin_data:/var/lib/pgadmin:rw"
    ports:
      - "8084:80"
